-- -- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

------------------
---- MONITORS ----
------------------
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

local terminal = "warp-terminal"
local files = "nautilus"
local editor = "code"
local browser = "zen-browser"

-------------------
---- AUTOSTART ----
-------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("systemctl --user restart xdg-desktop-portal-hyprland")
    hl.exec_cmd("$HOME/.config/hypr/initial-boot.sh")
    hl.exec_cmd("xhost +local:root")
    hl.exec_cmd("sleep 1 && pactl set-source-port alsa_input.pci-0000_06_00.6.analog-stereo analog-input-mic")
    hl.exec_cmd("kdeconnectd")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("bash -c 'wl-paste --watch cliphist store &'")
    hl.exec_cmd("ln -sf /run/media/skepr/Data/Github/ ~/Documents/Github")
    hl.exec_cmd(browser)
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("TERMINAL", "warp-terminal")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_MENU_PREFIX", "plasma-")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("CLUTTER_BACKEND", "wayland")

----------------------------
---- MAIN CONFIG & VARS ----
----------------------------
hl.config({
    input = {
        kb_layout = "us, ara",
        kb_options = "grp:win_space_toggle",
        repeat_rate = 50,
        repeat_delay = 300,
        sensitivity = 0,
        numlock_by_default = true,
        follow_mouse = 1,

        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            tap_to_click = true,
        },
    },

    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 0,
        resize_on_border = true,
        layout = "dwindle",
    },

    decoration = {
        rounding         = 35,
        active_opacity   = 0.85,
        inactive_opacity = 0.80,

        shadow           = {
            enabled = false,
        },

        blur             = {
            enabled = true,
            size = 3,
            passes = 2,
        },
    },

    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        mfact = 0.5,
        new_status = "master"
    }
})

--------------------
---- ANIMATIONS ----
--------------------

hl.animation({ leaf = "windows", enabled = true, speed = 6, bezier = "default" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, bezier = "default", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5, bezier = "default", style = "slide" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "default", style = "slide" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 4, bezier = "default", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 4, bezier = "default", style = "slide" })

----------------------
---- WINDOW RULES ----
----------------------
hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
    match = { class = "^(steam)$" },
    no_initial_focus = true,
    pin = true,
    workspace = 5
})
hl.window_rule({
    match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
    float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })


hl.window_rule({ match = { class = "^(calculator|galculator|blueman-manager|xdg-desktop-portal|Emulator)$" }, float = true })
hl.window_rule({ match = { class = "^(com\\.skepr\\.hodor)$" }, opacity = 1 })

hl.window_rule({
    match = { class = "^(xwaylandvideobridge)$" },
    no_initial_focus = true,
    no_focus = true,
    no_anim = true,
    max_size = { 1, 1 },
    opacity = 0.0
})

---------------------
---- KEYBINDINGS ----
---------------------
local mainMod = "SUPER"
hl.bind("SUPER + SHIFT + E", hl.dsp.group.toggle())

-- === Application Launchers ===
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + I", hl.dsp.exec_cmd(editor))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(files))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("dms ipc call processlist toggle"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("dms ipc call settings toggle"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("dms ipc call notepad toggle"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("dms ipc wallpaperCarousel toggle"))
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

-- === Security ===
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
hl.bind("XF86Display", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exit())
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("dms ipc call processlist toggle"))
hl.bind("CTRL + ALT + F3", hl.dsp.exec_cmd("sudo chvt 3"))

-- === Audio & Brightness Controls ===
local media_keys = {
    { "XF86AudioRaiseVolume",        "dms ipc call audio increment 3",           { locked = true, repeating = true } },
    { "XF86AudioLowerVolume",        "dms ipc call audio decrement 3",           { locked = true, repeating = true } },
    { "XF86AudioMute",               "dms ipc call audio mute",                  { locked = true } },
    { "XF86AudioMicMute",            "dms ipc call audio micmute",               { locked = true } },
    { "XF86AudioPause",              "dms ipc call mpris playPause",             { locked = true } },
    { "XF86AudioPlay",               "dms ipc call mpris playPause",             { locked = true } },
    { "XF86AudioPrev",               "dms ipc call mpris previous",              { locked = true } },
    { "XF86AudioNext",               "dms ipc call mpris next",                  { locked = true } },
    { "CTRL + XF86AudioRaiseVolume", "dms ipc call mpris increment 3",           { locked = true, repeating = true } },
    { "CTRL + XF86AudioLowerVolume", "dms ipc call mpris decrement 3",           { locked = true, repeating = true } },
    { "XF86MonBrightnessUp",         [[dms ipc call brightness increment 5 ""]], { locked = true, repeating = true } },
    { "XF86MonBrightnessDown",       [[dms ipc call brightness decrement 5 ""]], { locked = true, repeating = true } }
}
for _, k in ipairs(media_keys) do
    hl.bind(k[1], hl.dsp.exec_cmd(k[2]), k[3])
end

hl.bind(mainMod .. " + mouse:276", hl.dsp.exec_cmd("dms ipc call audio increment 3"))
hl.bind(mainMod .. " + mouse:275", hl.dsp.exec_cmd("dms ipc call audio decrement 3"))

-- === Color Picker ===
hl.bind("XF86Favorites", hl.dsp.exec_cmd("hyprpicker -a"), { repeating = true })

-- === Window Management ===
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))

-- === Focus & Window Movement (Loops) ===
local dirs = { left = "l", down = "d", up = "u", right = "r", H = "l", J = "d", K = "u", L = "r", P = "r" }
for key, dir in pairs(dirs) do
    if key ~= "L" then hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ direction = dir })) end
    if key ~= "P" and key ~= "L" then hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ direction = dir })) end
    hl.bind(mainMod .. " + CTRL + " .. key, hl.dsp.focus({ monitor = dir }))
    hl.bind(mainMod .. " + SHIFT + CTRL + " .. key, hl.dsp.window.move({ monitor = dir }))
end

-- === Column Navigation ===
hl.bind(mainMod .. " + Home", hl.dsp.focus({ window = "first" }))
hl.bind(mainMod .. " + End", hl.dsp.focus({ window = "last" }))

-- === Workspace Navigation ===
hl.bind(mainMod .. " + Page_Down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + Page_Up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("ALT + TAB", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("mouse:276", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("mouse:275", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + U", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + CTRL + I", hl.dsp.window.move({ workspace = "e-1" }))

-- === Move Workspaces ===
hl.bind(mainMod .. " + SHIFT + Page_Down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + SHIFT + Page_Up", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.window.move({ workspace = "e-1" }))

-- === Mouse Wheel Navigation ===
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + mouse_down", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mainMod .. " + CTRL + mouse_up", hl.dsp.window.move({ workspace = "e-1" }))

-- === Numbered Workspaces [1-10] ===
for i = 1, 10 do
    local key = tostring(i % 10)
    local ws = tostring(i)
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = ws }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = ws }))
end

-- === Column Management & Layout ===
hl.bind(mainMod .. " + bracketleft", hl.dsp.layout("preselect l"))
hl.bind(mainMod .. " + bracketright", hl.dsp.layout("preselect r"))
hl.bind(mainMod .. " + R", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + CTRL + F", hl.dsp.window.resize({ x = 100, y = 100, relative = false }))

-- === Mouse Dragging ===
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Move window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize window" })

-- === Manual Sizing & Keycodes ===
hl.bind(mainMod .. " + code:20", hl.dsp.window.resize({ x = -100, y = 0, relative = true }),
    { description = "Expand window left" })
hl.bind(mainMod .. " + code:21", hl.dsp.window.resize({ x = 100, y = 0, relative = true }),
    { description = "Shrink window left" })
hl.bind(mainMod .. " + minus", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + equal", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + minus", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + equal", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })

-- === Screenshots ===
hl.bind("Print", hl.dsp.exec_cmd("dms ipc call screenCaptureToolbar toggle"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("dms screenshot"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("dms screenshot window"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms screenshot full"))


require("dms.colors")
require("dms.outputs")
require("dms.cursor")
require("dms.windowrules")
